# Generated by Django 4.2.14 on 2024-12-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_shloka_chapter_slider_chapter_chapter_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='shloka',
            name='shlok_transalation_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shloka',
            name='shlok_transalation_hindi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
