# Generated by Django 4.2.14 on 2024-12-25 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_shloka_shlok_transalation_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shloka',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shlokas', to='books.chapter'),
        ),
    ]
