# Generated by Django 5.1.4 on 2024-12-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0012_alter_shloka_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shloka",
            name="shloka_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
