# Generated by Django 4.2.14 on 2025-01-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_shloka_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shloka',
            name='shlok_transalation_english',
        ),
        migrations.RemoveField(
            model_name='shloka',
            name='shlok_transalation_hindi',
        ),
    ]
