# Generated by Django 4.2.14 on 2025-01-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_shloka_shlok_transalation_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_number',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
