# Generated by Django 4.2.14 on 2025-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_section_section_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_number',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
