# Generated by Django 4.2.14 on 2025-01-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_section_section_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_image',
        ),
        migrations.AddField(
            model_name='section',
            name='section_slider',
            field=models.ImageField(blank=True, null=True, upload_to='section_slider/'),
        ),
    ]
